In [116]:
import torch

In [117]:
x = torch.tensor([1,2,3])
print(x.shape)
print(x)

torch.Size([3])
tensor([1, 2, 3])


In [118]:
x = torch.tensor([[1,2,3],[4,5,6]])
print(x.shape)
print(x)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [119]:
x = torch.empty(size=(3,3))
print(x)
print(x.shape)

tensor([[ 5.6418e-27,  3.1704e-41,  5.6416e-27],
        [ 3.1704e-41,  8.9683e-44,  0.0000e+00],
        [ 1.3452e-43,  0.0000e+00, -2.7318e-35]])
torch.Size([3, 3])


In [120]:
x = torch.zeros(size=(3,3))
print(x)
print(x.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([3, 3])


In [121]:
x = torch.ones(size=(3,3))
print(x)
print(x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.Size([3, 3])


In [122]:
x = torch.eye(3,3)
print(x)
print(x.shape)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
torch.Size([3, 3])


In [123]:
x = torch.rand(size=(3,3))
print(x)
print(x.shape)

tensor([[0.5622, 0.0929, 0.3406],
        [0.8798, 0.0266, 0.7322],
        [0.0600, 0.0586, 0.1759]])
torch.Size([3, 3])


In [124]:
x = torch.linspace(start=0.1,end=1,steps=10)
print(x)
print(x.shape)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
torch.Size([10])


In [125]:
x = torch.arange(4)
print(x.bool())
print(x.short())
print(x.long())
print(x.half())


tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)


In [126]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = x + y
print(z)

tensor([5, 7, 9])


In [127]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = torch.add(x,y)
print(z)

tensor([5, 7, 9])


In [128]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = x - y
print(z)


tensor([-3, -3, -3])


In [129]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = torch.sub(x,y)
print(z)


tensor([-3, -3, -3])


In [130]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = x * y
print(z)

tensor([ 4, 10, 18])


In [131]:
x = torch.tensor([1,2,3])
z = x * 5
print(z)


tensor([ 5, 10, 15])


In [132]:
x = torch.tensor([1,2,3])
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [133]:
x = torch.tensor([1,2,3])
y = torch.tensor([4,5,6])
z = torch.dot(x,y)
print(z)

tensor(32)


In [134]:
x = torch.tensor([[1,2,3],[4,5,6]])
sum_x = torch.sum(x,dim=0)
print(sum_x)

tensor([5, 7, 9])


In [135]:
x = torch.tensor([[1,2,3],[4,5,6]])
min_x= torch.min(x,dim=0)
print(min_x)

torch.return_types.min(
values=tensor([1, 2, 3]),
indices=tensor([0, 0, 0]))


In [136]:
x = torch.tensor([[1,2,3],[4,5,6]])
max_x= torch.max(x,dim=0)
print(max_x)

torch.return_types.max(
values=tensor([4, 5, 6]),
indices=tensor([1, 1, 1]))


In [137]:
x = torch.tensor([1,5,3])
y = torch.tensor([4,5,6])
z = torch.eq(x,y)
print(z)

tensor([False,  True, False])


In [138]:
x = torch.tensor([1,5,3,-1,-2,-22,-30, 30 , 5,4,3,20,43])
z = torch.clamp(x,min=0,max=10)
print(z)

tensor([ 1,  5,  3,  0,  0,  0,  0, 10,  5,  4,  3, 10, 10])


In [139]:
x = torch.arange(10)
print(x[x<2])
print(x[(x<2) & (x>8)])
print(x[(x<2) | (x>8)])
print(x[x.remainder(2)==0])

tensor([0, 1])
tensor([], dtype=torch.int64)
tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [140]:
print(torch.where(x>5,x,x*2))

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


In [141]:
print(torch.tensor([0,0,1,2,2,3,4]).unique())

tensor([0, 1, 2, 3, 4])


In [142]:
print(x.ndimension())

1


In [143]:
print(x.numel())

10


In [144]:
x = torch.arange(9)
print(x)
print('--------------------------------------')
a = x.view(3,3)
print(a)
print('--------------------------------------')
b =a.reshape(3,3)
print(b)
print('--------------------------------------')
print(a.t())
print('--------------------------------------')
print(a.transpose(0,1))
print('--------------------------------------')
print(a.permute(1,0))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
--------------------------------------
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
--------------------------------------
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
--------------------------------------
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
--------------------------------------
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
--------------------------------------
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


In [146]:
x = torch.tensor([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
z = x.view(-1)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
